# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: calc.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='calc.proto',
  package='helloworld',
  syntax='proto3',
  serialized_options=b'\n\033io.grpc.examples.helloworldB\017HelloWorldProtoP\001\242\002\003HLW',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\ncalc.proto\x12\nhelloworld\"B\n\x0b\x43\x61lcRequest\x12\x11\n\tfirstTerm\x18\x01 \x01(\t\x12\x12\n\nsecondTerm\x18\x02 \x01(\t\x12\x0c\n\x04oper\x18\x03 \x01(\t\"\x1c\n\tCalcReply\x12\x0f\n\x07message\x18\x01 \x01(\t2F\n\nCalculator\x12\x38\n\x04\x43\x61lc\x12\x17.helloworld.CalcRequest\x1a\x15.helloworld.CalcReply\"\x00\x42\x36\n\x1bio.grpc.examples.helloworldB\x0fHelloWorldProtoP\x01\xa2\x02\x03HLWb\x06proto3'
)




_CALCREQUEST = _descriptor.Descriptor(
  name='CalcRequest',
  full_name='helloworld.CalcRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='firstTerm', full_name='helloworld.CalcRequest.firstTerm', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='secondTerm', full_name='helloworld.CalcRequest.secondTerm', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='oper', full_name='helloworld.CalcRequest.oper', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=92,
)


_CALCREPLY = _descriptor.Descriptor(
  name='CalcReply',
  full_name='helloworld.CalcReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='helloworld.CalcReply.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=94,
  serialized_end=122,
)

DESCRIPTOR.message_types_by_name['CalcRequest'] = _CALCREQUEST
DESCRIPTOR.message_types_by_name['CalcReply'] = _CALCREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CalcRequest = _reflection.GeneratedProtocolMessageType('CalcRequest', (_message.Message,), {
  'DESCRIPTOR' : _CALCREQUEST,
  '__module__' : 'calc_pb2'
  # @@protoc_insertion_point(class_scope:helloworld.CalcRequest)
  })
_sym_db.RegisterMessage(CalcRequest)

CalcReply = _reflection.GeneratedProtocolMessageType('CalcReply', (_message.Message,), {
  'DESCRIPTOR' : _CALCREPLY,
  '__module__' : 'calc_pb2'
  # @@protoc_insertion_point(class_scope:helloworld.CalcReply)
  })
_sym_db.RegisterMessage(CalcReply)


DESCRIPTOR._options = None

_CALCULATOR = _descriptor.ServiceDescriptor(
  name='Calculator',
  full_name='helloworld.Calculator',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=124,
  serialized_end=194,
  methods=[
  _descriptor.MethodDescriptor(
    name='Calc',
    full_name='helloworld.Calculator.Calc',
    index=0,
    containing_service=None,
    input_type=_CALCREQUEST,
    output_type=_CALCREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_CALCULATOR)

DESCRIPTOR.services_by_name['Calculator'] = _CALCULATOR

# @@protoc_insertion_point(module_scope)
